### ISSUE TITLE
XGBoost model format is not forward compatible

### ISSUE THREAD

**Issue by PatWalters** [sutropub/OpenSOL#1]
Hi, 

First of all, thanks for publishing your paper and the associated code.   I noticed the melting point model in Models/xgboost_rdkit_2d_clustering_model.job was saved using joblib.   Unfortunately, the model will only work with XGBoost 1.5, which is somewhat outdated.  You may want to fix this to make the model work with newer versions of XGBoost.  It's really easy.   In a conda environment with XGBoost 1.5 do the following. 

```
import joblib
model = joblib.load("xgboost_rdkit_2d_clustering_model.job")
model.save_model("xgboost_rdkit_2d_clustering_model.json")
```

The json format model will work with newer versions of XGBoost.

**Comment by ichxw** [comment]
Hi Patrick, 
Thank you for bringing this issue to our attention. I greatly appreciate your insightful suggestion.
We have updated the xgboost model to json format and the corresponding code. Please note, in the updated README, it is recommended to use the latest version of RDkit to make it compatible with the newest numpy version. This is especially important considering the recent removal of numpy.float() in numpy in version 1.24.
Once again, I appreciate your valuable input. If you have any more suggestions or if there's anything else you'd like to discuss, please feel free to reach out.
Best, 
Xiangwei
