### ISSUE TITLE
# Columns in example doesn't match stored model

### ISSUE THREAD

**Issue by jlaw9** [sutropub/OpenSOL#3]
I'm following the example code, but I'm getting an error that the number of features / columns doesn't match. The stored model has 208 while the script is trying to give it 210.

```
$ python solubility_model.py -j Prediction -m xgboost -dscr rdkit_2d -s clustering -i 'O=C(O)C=1C=CC=CC1OC(=O)C' -o aspirin.csv
```
gives the error
```
xgboost.core.XGBoostError: [01:13:00] /workspace/src/learner.cc:1462: 
Check failed: learner_model_param_.num_feature >= p_fmat->Info().num_col_ (208 vs. 210) : 
Number of columns does not match number of features in booster.
```

I'm assuming the xgboost stored model at `Models/xgboost_rdkit_2d_clustering_model.json` needs to be updated

**Comment by ichxw** [comment]
Thank you for bringing this to our attention. Please roll back your RDKit to an earlier version to use the model. We are working on fixing the compatibility issue with RDKit and other packages and will address it in the next update.

**Comment by jlaw9** [comment]
Ok thank you, I downgraded to `rdkit-2022.9.5`, and it seems to be working now.
